<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pay now_iframe-3ds</name>
   <tag></tag>
   <elementGuidId>8911f9b5-630c-40a3-b23f-600b1417e8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.iframe-3ds</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1dd7c4c7-cdc9-467d-8125-0fb6fc724dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3ds-iframe</value>
      <webElementGuid>4786d879-db20-432e-884b-bea113d8df36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-3ds</value>
      <webElementGuid>93b3cd8f-a263-42a3-a5c5-eda7c526a3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.sandbox.midtrans.com/v2/token/rba/redirect/48111111-1114-91984140-48ba-442a-ae10-b757b0acd576</value>
      <webElementGuid>b21c8a64-7ba1-4b0f-8307-0818d6a7d014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/iframe[@class=&quot;iframe-3ds&quot;]</value>
      <webElementGuid>a7caea1e-f800-4e9e-a91f-e616167b62f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Object Repo by Record/button-OK-Declined/Page_Sample Store/iframe_concat(id(, , snap-midtrans, , ))_po_5c513f</value>
      <webElementGuid>74e4d970-2f6a-438a-8f1b-eba74c7d232e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/iframe</value>
      <webElementGuid>d764a856-bc0a-451b-8ea4-80856fc4052d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3f112300-bb6f-4d7f-8c09-48917f31181a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = '3ds-iframe' and @src = 'https://api.sandbox.midtrans.com/v2/token/rba/redirect/48111111-1114-91984140-48ba-442a-ae10-b757b0acd576']</value>
      <webElementGuid>ac5b9bc3-477e-48b9-921a-97fa61ed0e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
