<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amountTotalHeader</name>
   <tag></tag>
   <elementGuidId>90218488-c1b6-4885-9de8-15c8c1ef9374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='order-modal-body']//div[@class='header-amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='order-modal-body']//div[@class='header-amount']</value>
      <webElementGuid>791d4c0c-1f87-43ba-9d27-bc1d6eb654b5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
