<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe1</name>
   <tag></tag>
   <elementGuidId>7162d46a-044a-4ab3-9dc4-c8de47bc3098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.iframe-3ds</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a8f41401-4f2a-46cd-97c1-8bd708f7e874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3ds-iframe</value>
      <webElementGuid>33c16d28-79a6-4480-8d56-bdae0dd73660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-3ds</value>
      <webElementGuid>6f7e822a-cfa2-4088-9c42-b2efab033c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.sandbox.midtrans.com/v2/token/rba/redirect/48111111-1114-ef374660-da26-41d9-a4fe-13277d265568</value>
      <webElementGuid>1208878c-44d3-49ec-b1b3-32e505233364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/iframe[@class=&quot;iframe-3ds&quot;]</value>
      <webElementGuid>e2db7185-03d7-4169-b602-d27f96ff6d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Object Repo by Record/demo-midtrans/iframe2</value>
      <webElementGuid>55a4d3fe-a310-43b4-a05a-7c572ebe6957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/iframe</value>
      <webElementGuid>d5af45c1-31bd-44ec-959e-9381f578c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e6218839-ae4f-4e37-99db-c564a9674071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = '3ds-iframe' and @src = 'https://api.sandbox.midtrans.com/v2/token/rba/redirect/48111111-1114-ef374660-da26-41d9-a4fe-13277d265568']</value>
      <webElementGuid>f81099c6-af84-4eee-b49e-67bc704e93e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
