<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passTransaction</name>
   <tag></tag>
   <elementGuidId>d416f505-146c-4b8d-8b28-f9f9c88adf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaRes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PaRes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>492ba90c-536c-46e6-8184-ff7a79735767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b84b0d4b-b9c4-4ad6-8cf8-557eb0ebb577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-xs</value>
      <webElementGuid>59114071-faa6-4953-9054-3124262b25fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaRes</value>
      <webElementGuid>b68cb092-7918-499b-ab7c-e07d86273ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaRes</value>
      <webElementGuid>cbd2e3f5-9f25-493a-ac00-1442bc9f14b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>112233</value>
      <webElementGuid>c936e1c5-8abb-4676-8d39-bb73428c246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaRes&quot;)</value>
      <webElementGuid>80b9621a-6b24-424d-81df-345d2f9f451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Object Repo by Record/Page_Sample Store/iframe1</value>
      <webElementGuid>688aa421-269d-482e-902c-202bf92c3d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PaRes']</value>
      <webElementGuid>f4bc5971-1e8a-4540-8685-bc1f7afd16cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='acsForm']/div[5]/div/input</value>
      <webElementGuid>1fdd1a61-0904-44d1-be7e-93e11492f227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>467fcf3f-154b-4ed3-a2be-775e2727f225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'PaRes' and @name = 'PaRes' and @placeholder = '112233']</value>
      <webElementGuid>2aae0ab0-cd75-4256-ba0f-a0489d11e7ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
